### ISSUE TITLE
Error: Objecttype 'METADATA' has no len() 

### ISSUE THREAD

**Issue by phil100vol** [augmentedstartups/YOLOv4-Tutorials#6]
Hi,

i am trying to get an minimal example to run using my rtsp camera. Every time the code stops with the following error:

`  File "mini.py", line 139, in YOLO
    detections = darknet.detect_image(netMain, metaMain, darknet_image, thresh=0.25)    # Detection occurs at this line and return detections, for customize we can change the threshold.                                                                                   
  File "/home/cctv/darknet/darknet.py", line 174, in detect_image
    do_nms_sort(detections, num, len(class_names), nms)
TypeError: object of type 'METADATA' has no len()
`
Do you know how to solve this or have a glue what I am doing wrong?

Thanks for your help

Phil

**Comment by MysticCoss** [comment]
Hi, can  you provide which version of python you are using?

**Comment by phil100vol** [comment]
Hi,

```
python3 --version
Python 3.8.2
```

**Comment by MysticCoss** [comment]
It's totally darknet.py error not this project error. 
Here is the quick guide:
If you have a quick look at darknet.py you should know what is METADATA
`class METADATA(Structure):
    _fields_ = [("classes", c_int),
                ("names", POINTER(c_char_p))]`
_classes_ is total number of classes
_names_ is a list of class names.
_len(METADATA)_ is actually total number of classes.
So instead of using _len(METADATA)_ you can add a paramenter to pass _METADATA.classes_ to function

Note: incase you need help about METADATA not iterable, the solution for it is replace enumerate(METADATA) with a simple list of class names, which luckily we already have: 
`    if altNames is None:`
`        try:`
`            with open(metaPath) as metaFH:`
`                metaContents = metaFH.read()`
`                import re`
`                match = re.search("names *= *(.*)$", metaContents, re.IGNORECASE | re.MULTILINE)`
`                if match:`
`                    result = match.group(1)`
`                else:`
`                    result = None`
`                try:`
`                    if os.path.exists(result):`
`                        with open(result) as namesFH:`
`                            namesList = namesFH.read().strip().split("\n")`
`                            altNames = [x.strip() for x in namesList]`
`                except TypeError:`
`                    pass`
`        except Exception:`

**Comment by MysticCoss** [comment]
I can not import darknet.py in python 3.8 due to CDLL change, can you provide possible fix?

**Comment by phil100vol** [comment]
Changing the len(METADATE) to just an integer (for try) 

`do_nms_sort(detections, num, 2, nms)`

let me run in the METADATE object not iterable error.
```
  File "/home/cctv/darknet/darknet.py", line 175, in detect_image
    predictions = remove_negatives(detections, class_names, num)
  File "/home/cctv/darknet/darknet.py", line 156, in remove_negatives
    for idx, name in enumerate(class_names):
TypeError: 'METADATA' object is not iterable
```

I dont understand your fix: Shall i change the remove_negative(...) function because the error message hints to this line

> I can not import darknet.py in python 3.8 due to CDLL change, can you provide possible fix?

I followed a guide from the net and was happy it runs without any big changes

**Comment by MysticCoss** [comment]
The interger you mentioned is actually the number of classes in the yolo.names file. So you can just simply add 1 more argument and pass it to the func. I assume you fixed it.
Now the remove_negative takes METADATA as argument and loop through it. But the use of _METADATA_ is just taking class name.
You can pass there a simple _list_ which contain all classnames instead of _METADATA_
```
def remove_negatives(detections, number_class, class_list, num):
    """
    Remove all classes with 0% confidence within the detection
    """
    predictions = []
    for j in range(num):
        for idx, name in enumerate(class_list):
        # for name in class_list:
            if detections[j].prob[idx] > 0:
                bbox = detections[j].bbox
                bbox = (bbox.x, bbox.y, bbox.w, bbox.h)
                predictions.append((name, detections[j].prob[idx], (bbox)))
    return predictions
```
And 
`detections = darknet.detect_image(netMain, metaMain, metaMain.classes, namesList ,darknet_image)`
Can you give me link to the guide, the CDLL in py3.8 has changed but i dont know how to work with it cuz im new to python

**Comment by phil100vol** [comment]
Of course I give you the link:
[https://robocademy.com/2020/05/01/a-gentle-introduction-to-yolo-v4-for-object-detection-in-ubuntu-20-04/](url)

I had to do some changes on your code. The arguments didn't match:
`detections = darknet.detect_image(netMain, class_list , darknet_image , class_list)`

Now it runs. I can print the detentions :-D
